console.log("This is a variable page");
var a=5;
let b=6;
let c="happy";
const d="5";
let _a="RK and sk";
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(_a);
console.log(a+b+c+d+_a);
console.log(a+","+b+","+c+","+d+","+_a+",");
// var 55a=10;
// console.log(55a);
console.log(a+b);
console.log(c+_a);
console.log(f);
var f=b+d;
console.log(f);
typeof(f);